spring.datasource.url=jdbc:h2:${DATABASE_URL:file:./../../database/fujitsu_db;AUTO_SERVER=TRUE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD: }

spring.sql.init.data-locations=file:./../../database/init/schema.sql
spring.sql.init.mode=always