spring.sql.init.data-locations=\
  classpath*:sql/init/regions.sql,\
  classpath*:sql/init/measurements.sql,\
  classpath*:sql/init/vehicle_types.sql,\
  classpath*:sql/init/air_temperature_fees.sql,\
  classpath*:sql/init/wind_speed_fees.sql.sql,\
  classpath*:sql/init/weather_phenomenon_fees.sql,\
  classpath*:sql/init/regional_based_fees.sql