spring.datasource.url=jdbc:h2:${DATABASE_URL:mem:fujitsu_db}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}

spring.sql.init.schema-locations=classpath:sql/schema.sql

spring.sql.init.mode=always