create table if not exists regions (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    wmo_code varchar(20) not null
);

create table if not exists measurements (
    id bigint generated by default as identity primary key,
    region_id bigint not null,
    air_temperature decimal(4, 1) not null,
    wind_speed decimal(4, 1) not null,
    weather_phenomenon varchar(255) not null,
    measured_at timestamp not null, -- h2 doesn't have timestamptz :c | TO BE REPLACED
    constraint fk_regions_measurements foreign key (region_id) references regions(id)
);

create table if not exists vehicle_types (
    id bigint generated by default as identity primary key,
    type varchar(20) not null
);

/**
Fees
 */

create table if not exists air_temperature_fees (
    id bigint generated by default as identity primary key,
    vehicle_type_id bigint,
    min_temperature decimal(4, 1) not null,
    max_temperature decimal(4, 1) not null,
    fee decimal(10, 2) not null,
    is_allowed boolean default true,
    constraint fk_vehicle_types_temp foreign key (vehicle_type_id) references vehicle_types(id)
);

create table if not exists regional_based_fees (
    id bigint generated by default as identity primary key,
    region_id bigint not null,
    vehicle_type_id bigint,
    fee decimal(10, 2) not null,
    is_allowed boolean default true,
    constraint fk_regions foreign key (region_id) references regions(id),
    constraint fk_vehicle_types_reg foreign key (vehicle_type_id) references vehicle_types(id)
);

create table if not exists wind_speed_fees (
    id bigint generated by default as identity primary key,
    vehicle_type_id bigint,
    min_wind_speed decimal(4, 1) not null,
    max_wind_speed decimal(4, 1) not null,
    fee decimal(10, 2) not null,
    is_allowed boolean default true,
    constraint fk_vehicle_types_wind foreign key (vehicle_type_id) references vehicle_types(id)
);

create table if not exists weather_phenomenon_fees (
    id bigint generated by default as identity primary key,
    vehicle_type_id bigint,
    weather_phenomenon varchar(255),
    fee decimal(10, 2) not null,
    is_allowed boolean default true,
    constraint fk_vehicle_types_weather foreign key (vehicle_type_id) references vehicle_types(id)
);