env.ALLOWED_ORIGIN_PATTERN=${ALLOWED_ORIGIN_PATTERN:*}
env.ADMIN_USERNAME = ${ADMIN_USERNAME:admin}
env.ADMIN_PASSWORD = ${ADMIN_PASSWORD:admin}
env.USER_USERNAME = ${USER_USERNAME:user}
env.USER_PASSWORD = ${USER_PASSWORD:user}
env.JWT_SECRET = ${JWT_SECRET}

env.WEATHER_SYNC_CRON_SCHEDULE = ${WEATHER_SYNC_CRON_SCHEDULE:0 15 * * * *}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/api/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/v3/api-docs