# Stage 1: Build
FROM eclipse-temurin:25-jdk-jammy AS build
WORKDIR /app
COPY . .
RUN chmod +x gradlew
RUN ./gradlew clean build -x test

# Stage 2: Run
FROM eclipse-temurin:25-jre-jammy
WORKDIR /app
COPY --from=build /app/rest-app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]